In [1]:
import numpy

In [2]:
vettore = numpy.array([3, 7, 10, 4, 5, 3, 8, 12])

In [7]:
vettore[:6]

array([ 3,  7, 10,  4,  5,  3])

In [8]:
for elemento in vettore:
    doppio = elemento*2
    print(f'Il doppio di {elemento} è {doppio}')

Il doppio di 3 è 6
Il doppio di 7 è 14
Il doppio di 10 è 20
Il doppio di 4 è 8
Il doppio di 5 è 10
Il doppio di 3 è 6
Il doppio di 8 è 16
Il doppio di 12 è 24


In [9]:
matrice = numpy.array( [ [1,2,3,4,5] , [9,8,7,6,5], [4,4,5,5,1] ])


In [10]:
matrice

array([[1, 2, 3, 4, 5],
       [9, 8, 7, 6, 5],
       [4, 4, 5, 5, 1]])

In [11]:
matrice[1,3]

6

In [13]:
matrice[:,3]

array([4, 6, 5])

In [14]:
sotto_matrice = matrice[1:, 1:4]

In [15]:
sotto_matrice

array([[8, 7, 6],
       [4, 5, 5]])

In [16]:
sotto_matrice[1,1] = 30

In [17]:
sotto_matrice

array([[ 8,  7,  6],
       [ 4, 30,  5]])

In [18]:
matrice

array([[ 1,  2,  3,  4,  5],
       [ 9,  8,  7,  6,  5],
       [ 4,  4, 30,  5,  1]])

In [19]:
copia_matrice = matrice

In [20]:
copia_matrice[0,0] = 100

In [21]:
copia_matrice

array([[100,   2,   3,   4,   5],
       [  9,   8,   7,   6,   5],
       [  4,   4,  30,   5,   1]])

In [22]:
matrice

array([[100,   2,   3,   4,   5],
       [  9,   8,   7,   6,   5],
       [  4,   4,  30,   5,   1]])

In [23]:
sotto_matrice = matrice[:, :3].copy()

In [24]:
sotto_matrice[0,0] = -1

In [25]:
sotto_matrice

array([[-1,  2,  3],
       [ 9,  8,  7],
       [ 4,  4, 30]])

In [26]:
matrice

array([[100,   2,   3,   4,   5],
       [  9,   8,   7,   6,   5],
       [  4,   4,  30,   5,   1]])

In [35]:
vettore1 = numpy.array([1,2,3,4])
vettore2 = numpy.array([9,6,4,4])

In [36]:
(vettore1 + 2*vettore2)**2

array([361, 196, 121, 144], dtype=int32)

In [44]:
matrice1 = numpy.array([[[1,2], [2,3]],[[5,6],[8,10]]])

In [45]:
matrice1

array([[[ 1,  2],
        [ 2,  3]],

       [[ 5,  6],
        [ 8, 10]]])

In [46]:
matrice1[1,0,1]

6

In [47]:
vettore2

array([9, 6, 4, 4])

In [48]:
vettore2**2

array([81, 36, 16, 16], dtype=int32)

In [53]:
numpy.sqrt(vettore2)

array([3.        , 2.44948974, 2.        , 2.        ])

In [54]:
numpy.sin(vettore2)

array([ 0.41211849, -0.2794155 , -0.7568025 , -0.7568025 ])